### ISSUE TITLE
NS is a reserved prefix for Apple classes

### ISSUE THREAD

**Issue by 3lvis** [terhechte/CoreValue#1]
NS is a reserved prefix for Apple classes, using NS in your own classes is a bad practice. Any plans for fixing this?

https://github.com/terhechte/CoreValue/blob/cd34a93606994522f84f48ab1f7230c8b96ac5ba/CoreValue/CoreValue.swift#L230-L232

**Comment by terhechte** [comment]
Oh right. I honestly totally forgot about that when drafting the protocols. Will quickly fix it. Thanks for pointing it out!

**Comment by 3lvis** [comment]
:heart:

**Comment by terhechte** [comment]
Just released 0.1.2 which fixes this :)
