### ISSUE TITLE
Duplicate entries

### ISSUE THREAD

**Issue by leandromperez** [terhechte/CoreValue#19]
Hello,
I created this test for duplicate entries:
Save StoredShopEmployee A.
**count of StoredShopEmployee is 1.**

StoredEmployeeShop 1 and StoredEmployeeShop 2 have a copy of StoredShopEmployee A.
Save Shop 1
Save Shop 2.
**count of StoredShopEmployee is 3 instead of 1.**

It looks like when you save the shops is not checking if Employee A is already saved and it is creating new entries.

  ```
  var employeesCount : Int{
        let employees : [StoredShopEmployee] = try! StoredShopEmployee.query(context, predicate: nil)
        return  employees.count
    }
    
    func testDuplicateEntries() {
        let beforeCount = self.employeesCount
        
        var employee = StoredShopEmployee(objectID: nil, name: "John", age: 18, position: "Clerk", department: "All", job: "Clerk", shop:nil)
        
        try! employee.save(context)
    
        XCTAssertEqual(beforeCount + 1, self.employeesCount)
        
        var shop1 = StoredEmployeeShop(objectID: nil, name: "Carpet shop 1", employees: [employee])
        var shop2 = StoredEmployeeShop(objectID: nil, name: "Carpet shop 2", employees: [employee])

        try! shop1.save(context)
        try! shop2.save(context)
        
        XCTAssertEqual(beforeCount + 1, self.employeesCount)
    }
```

**Comment by terhechte** [comment]
Hey, would you also be interested in having a go and trying to fix this issue? I suppose it would be sufficient to do a check to see if the `employee` already possesses an objectiID. CoreValue's actual code is fairly small.

**Comment by terhechte** [comment]
Thanks to @leandromperez PR this is now fixed! 👍  👏🎉

**Comment by leandromperez** [comment]
Hi,
I wrote a short thing about the bug. Perhaps you're interested in reading
about it.
Cheers

**Comment by leandromperez** [comment]
https://medium.com/@826a8f040c3e/9ef1a42c83b6
