### ISSUE TITLE
Push v0.1.3 to cocoapods, please?

### ISSUE THREAD

**Issue by levibostian** [terhechte/CoreValue#4]
Cocoapods currently has [v0.1.2](https://cocoapods.org/?q=corevalue) live for the library. The repo Podspec however says it is updated to v0.1.3. 

So in order for me to download the v0.1.3 to cocoapods, I am guessing you need to push an update up?

Thanks

**Comment by terhechte** [comment]
Hey,

sorry should work now. When I tried it earlier cocoapods always failed with an error
(`- WARN  | url: There was a problem validating the URL https://github.com/terhechte/CoreValue.`)
After that I kinda forgot about it.

Today I tried again, and it still ran into the same error. However after some googling I read that one just has to re-run cocoa pods until works. So I ran the required update commands around 15 times today, and then it suddenly worked. Awful experience, but 0.1.6 is out, even on cocoapods.
