### ISSUE TITLE
CVManagedPersistentStruct not found

### ISSUE THREAD

**Issue by tkohout** [terhechte/CoreValue#8]
In version 0.1.3 the CVManagedPersistentStruct is not made public and it is not accessible from other module.

Quick fix was for me to add to my code (_CVManagedPersistentStruct is public):

`
public protocol CVManagedPersistentStruct : _CVManagedPersistentStruct {
    typealias StructureType = Self
}
`

Thanks, and keep up the good work

**Comment by terhechte** [comment]
Thanks!

I've just updated the release to 0.1.6 which includes this change among other changes. It's available via cocoapods and carthage.
